version: "3.9"
services:
  redis:
    container_name: redis
    image: redis:4.0-alpine
    command:
      - 'redis-server'
      - '--loglevel notice'
      - '--databases 2'
      - '--save 900 1'
      - '--save 300 10'
      - '--save 60 10000'
      - '--maxmemory -50mb'
      - '--maxmemory-policy noeviction'
      - '--requirepass redis'
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
volumes: 
  redis:
    driver: local