version: '3.3'
services:
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    user: root
    # specify prometheus configuration file 
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      # host volume
      - ./prometheus/:/etc/prometheus/
      # named volume
      - prometheus_data:/prometheus
    ports:
      - 9090:9090
    restart: on-failure

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: root
    volumes: 
      # ro - read-only mode
      - ./grafana/prometheus-datasource.yml:/etc/grafana/provisioning/datasources/prometheus-datasource.yml:ro
      - grafana_data:/var/lib/grafana
    ports: 
      - 3000:3000

volumes: 
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
