version: '3.3'
services:
  db:
    image: mysql:8.0.23
    command: --lower-case-table-names=1
    restart: always
    cap_add: 
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'admin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'admin'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: 
    driver: local