version: '3.3'

services:
  localstack:
    # localstack-full contains ui panel, but it will be removed in the next version
    # TODO: replace image to localstack/localstack
    image: localstack/localstack-full
    network_mode: bridge
    ports:
      - '4566:4566'
      - '4571:4571'
      - '8181:8080'
    environment:
      - SERVICES=sns
      - DEBUG=1
      - DEFAULT_REGION=eu-central-1
      - HOSTNAME=localhost
      # TODO: configure volumes to use /usr/docker folder
      - DATA_DIR=/tmp/localstack/data
      - PORT_WEB_UI=8080
      - DOCKER_HOST=unix:///var/run/docker.sock
      - HOST_TMP_FOLDER=/tmp
    volumes:
      - ./data:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock